services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./process:/app/process

  pipeline:
    build:
      context: .
      dockerfile: Dockerfile.pipeline
    volumes:
      - ./process:/app/process
