services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./process:/app/process

  pipeline:
    build:
      context: ./pipeline
      dockerfile: Dockerfile
    volumes:
      - ./process:/app/process
